-   repo: git@github.com:asottile/reorder_python_imports
    sha: v0.3.1
    commit_stage: [commit]
    hooks:
    -   id: reorder-python-imports
        stages: commit_stage

-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    commit_stage: [commit]
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: debug-statements
    # See https://github.com/pre-commit/pre-commit-hooks/issues/173 https://github.com/pre-commit/pre-commit/issues/191
    -   id: detect-aws-credentials
        exclude: ^(pyzomato)$
    -   id: detect-private-key     # This hook is broken for submodules
        exclude: ^(pyzomato)$
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: flake8
        stages: commit_stage

-   repo: local
    push_stage: [push]
    commit_stage: [commit]

    hooks:
    #-   id: check-tox
        #name: Tox Tests
        #entry: python -m tox
        #stages: push_stage
        #language: system
        #files: \.py$
    -   id: check-nose2
        name: Nose2 Tests
        entry: sh -c "make test"
        #stages: commit_stage
        language: system
        files: \.py$
